const { Dog } = require('../models');

const dogData = [
  { dog_name: 'Valentina', size: 'medium', owner_id: 15 },
  { dog_name: 'Caresa', size: 'large', owner_id: 10 },
  { dog_name: 'Nancie', size: 'large', owner_id: 8 },
  { dog_name: 'Riannon', size: 'large', owner_id: 1 },
  { dog_name: 'Stephi', size: 'medium', owner_id: 16 },
  { dog_name: 'Maxy', size: 'small', owner_id: 21 },
  { dog_name: 'Gustavus', size: 'large', owner_id: 10 },
  { dog_name: 'Ancell', size: 'large', owner_id: 13 },
  { dog_name: 'Haydon', size: 'small', owner_id: 15 },
  { dog_name: 'Esme', size: 'small', owner_id: 19 },
  { dog_name: 'Nina', size: 'small', owner_id: 18 },
  { dog_name: 'Cherice', size: 'medium', owner_id: 20 },
  { dog_name: 'Emalee', size: 'large', owner_id: 1 },
  { dog_name: 'Walden', size: 'large', owner_id: 23 },
  { dog_name: 'Sherrie', size: 'medium', owner_id: 24 },
  { dog_name: 'Garth', size: 'small', owner_id: 16 },
  { dog_name: 'Olivia', size: 'large', owner_id: 21 },
  { dog_name: 'Matty', size: 'medium', owner_id: 8 },
  { dog_name: 'Payton', size: 'large', owner_id: 3 },
  { dog_name: 'Dicky', size: 'medium', owner_id: 5 },
  { dog_name: 'Skye', size: 'medium', owner_id: 21 },
  { dog_name: 'Sherwynd', size: 'large', owner_id: 13 },
  { dog_name: 'Dylan', size: 'medium', owner_id: 12 },
  { dog_name: 'Donica', size: 'small', owner_id: 20 },
  { dog_name: 'Phaedra', size: 'medium', owner_id: 21 },
  { dog_name: 'Charmaine', size: 'medium', owner_id: 20 },
  { dog_name: 'Katha', size: 'large', owner_id: 5 },
  { dog_name: 'Gennifer', size: 'medium', owner_id: 11 },
  { dog_name: 'Cele', size: 'medium', owner_id: 13 },
  { dog_name: 'Kristoforo', size: 'medium', owner_id: 19 },
  { dog_name: 'Phylys', size: 'medium', owner_id: 13 },
  { dog_name: 'Maryl', size: 'medium', owner_id: 13 },
  { dog_name: 'Galvan', size: 'small', owner_id: 15 },
  { dog_name: 'Blane', size: 'large', owner_id: 23 },
  { dog_name: 'Hercules', size: 'medium', owner_id: 9 },
  { dog_name: 'Armando', size: 'medium', owner_id: 13 },
  { dog_name: 'Lucais', size: 'medium', owner_id: 10 },
  { dog_name: 'Cacilie', size: 'small', owner_id: 14 },
  { dog_name: 'Shelton', size: 'small', owner_id: 24 },
  { dog_name: 'Armando', size: 'small', owner_id: 16 },
  { dog_name: 'Adelind', size: 'large', owner_id: 17 },
  { dog_name: 'Laney', size: 'small', owner_id: 22 },
  { dog_name: 'Giustino', size: 'medium', owner_id: 2 },
  { dog_name: 'Sharia', size: 'large', owner_id: 20 },
  { dog_name: 'Ranee', size: 'small', owner_id: 18 },
  { dog_name: 'Amandi', size: 'medium', owner_id: 7 },
  { dog_name: 'Dolly', size: 'large', owner_id: 17 },
  { dog_name: 'Nanni', size: 'medium', owner_id: 16 },
  { dog_name: 'Edna', size: 'large', owner_id: 18 },
  { dog_name: 'Buffy', size: 'medium', owner_id: 3 },
  { dog_name: 'Marcia', size: 'large', owner_id: 10 },
  { dog_name: 'Solomon', size: 'medium', owner_id: 22 },
  { dog_name: 'Maia', size: 'medium', owner_id: 25 },
  { dog_name: 'Zebadiah', size: 'small', owner_id: 21 },
  { dog_name: 'Stearn', size: 'large', owner_id: 5 },
  { dog_name: 'Elenore', size: 'medium', owner_id: 12 },
  { dog_name: 'Sayre', size: 'medium', owner_id: 21 },
  { dog_name: 'Annabell', size: 'large', owner_id: 20 },
  { dog_name: 'Kimmie', size: 'medium', owner_id: 14 },
  { dog_name: 'Clevie', size: 'medium', owner_id: 2 },
  { dog_name: 'Jerrine', size: 'medium', owner_id: 24 },
  { dog_name: 'Lynnelle', size: 'large', owner_id: 22 },
  { dog_name: 'Amalie', size: 'large', owner_id: 6 },
  { dog_name: 'Chaunce', size: 'large', owner_id: 8 },
  { dog_name: 'Neal', size: 'medium', owner_id: 23 },
  { dog_name: 'Thaddus', size: 'large', owner_id: 18 },
  { dog_name: 'Adair', size: 'large', owner_id: 1 },
  { dog_name: 'Pip', size: 'medium', owner_id: 19 },
  { dog_name: 'Constancy', size: 'small', owner_id: 24 },
  { dog_name: 'Ignazio', size: 'large', owner_id: 4 },
  { dog_name: 'Engelbert', size: 'medium', owner_id: 25 },
  { dog_name: 'Annabal', size: 'large', owner_id: 25 },
  { dog_name: 'Anette', size: 'small', owner_id: 8 },
  { dog_name: 'Nelie', size: 'medium', owner_id: 12 },
  { dog_name: 'Conny', size: 'small', owner_id: 11 },
];

const seedDog = () => Dog.bulkCreate(dogData);

module.exports = seedDog;
